CREATE DATABASE Ecommerce_Application

USE Ecommerce_Application

-- customers table
CREATE TABLE CUSTOMERS (
CUSTOMERS_ID INT identity PRIMARY KEY,
NAME VARCHAR (90),
EMAIL VARCHAR (80),
PASSWORD VARCHAR (90))

-- products table
CREATE TABLE PRODUCTS (
PRODUCT_ID INT identity PRIMARY KEY,
NAME VARCHAR (90),
PRICE INT ,
DESCRIPTION VARCHAR(90),
stockQuantity varchar(90))

--cart table
CREATE TABLE CART (
CART_ID INT identity PRIMARY KEY,
CUSTOMERS_ID INT,
FOREIGN KEY (CUSTOMERS_ID) REFERENCES CUSTOMERS(CUSTOMERS_ID),
PRODUCT_ID INT,
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
QUANTITY INT) 


--orders table
CREATE TABLE ORDERS(
ORDER_ID INT identity Primary Key,
CUSTOMER_ID INT,
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
ORDER_DATE DATE,
TOTAL_PRICE INT,
SHIPPING_ADDRESS VARCHAR(100))


 --order_items table
 DROP TABLE ORDER_ITEM;
 CREATE TABLE ORDER_ITEM(
 ORDER_ITEM_ID INT identity Primary Key,
 ORDER_ID INT,
 FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
 PRODUCT_ID INT,
 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
 QUANTITY INT)

 